[tool.poetry]
name = "learn-pyspark"
version = "0.1.0"
description = ""
authors = ["PeterPaton123 <peter-paton@outlook.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
